---
title: "Basics for R"
author: "SijingQiu"
date: "2020/8/21"
output: html_document
---

#增加变量
```{r}
mydata1 <- data.frame(x1 = c(1,2,3,4),
					  x2 = c(3,4,1,5))


mydata1$sum <- mydata1$x1 + mydata1$x2 #直接增加变量sum
mydata2$mean <- mydata1$sum/2 #直接增加变量mean
mydata1 <- transform(mydata1,sum1=x1+x2，
					 mean1=(x1+x2)/2)

```

#变量删除

```{r}
mydata1$sum <- MULL
mydata1

```

#变量重新命名

```{r}
df <- mydata1
fix(df)
names(df)
names(df)[1:3] <- c('a1','b1','c1') #将df数据框前三个字段名称变为abc
df

```

#缺失值处理

```{r}
x <- c(1:3,5,7,Na,9)
sum(x)
sum(x,na.rm = T) #忽略缺失值

```

#数据排序

```{r}
df[order(-df$a1),] #按照a1从大到小排列，前面加-表示从大到小
df[order(df$a1),] 

#利用第三方包排序
library(plyr)
arrange(df,b1) #不加负号从小到大，加了负号相反

df <- data.frme (id=1:4,
				 weight = c(20,27,24,22),
				 size = c("small","large","medium","large"))
arrange(df,size,weight) #size是第一顺序，weight是第二顺序
df[order(df$size,df$weight),]

```


#数据集合并
列合并是增加行，merge.data.frame
行合并是增加列，rbind

```{r}

df1<-data.frame(name=c('小明','小王','xiaohua'),article=c(100,50,75))
df2<-data.frame(name=c('小明','小王','xiaohua'),math=c(70,50,85))
#列合并，要求具有共同的列名称
total<-merge.data.frame(df1,df2,by='name') #根据共同的字段name来进行合并
#行合并，要求列的名称保持一致
dfA <- data.frame( Subject = c(1, 1, 2, 2), Response = c("X", "X", "X", "X") )
dfB <- data.frame( Subject = c(1, 2, 3), Response = c("Z", "Y", "Z") )
df <- rbind(dfA, dfB)
```

